### ISSUE TITLE
Animating 2 widgets

### ISSUE THREAD

**Issue by kittykatattack** [mdgriffith/elm-html-animation#4]
Hello!

I have a question about the best way to handle two simple, but very different animations in single module. I have two animation styles defined in my `model` like this:
```
, styleInfo =
      UI.init
        [ Top -10.0 Px 
        , Opacity 0.5
        ]
  , styleMeter =
      UI.init
        [ Width 450.0 Px 
        ]
```
The `styleInfo` animates the position of an information drawer that slides up from the bottom. The `styleMeter` animates the width of a scale meter.

I have some actions that update the animations like this:
```
  -- The animation actions for the info drawer  
  ShowInfo ->
      let
        model' =
          { model 
              | infoBoxIsOpen = True
          }
      in
        UI.animate
          |> UI.spring UI.wobbly
          |> UI.props
              [ Top (UI.to -300) Px
              , Opacity (UI.to 1)
              ]
          |> onMenu model'

    HideInfo ->
      let
        model' =
          { model 
              | infoBoxIsOpen = False
          }
      in
      UI.animate
        |> UI.spring UI.wobbly
        |> UI.props
            [ Top (UI.to -10) Px
            , Opacity (UI.to 0.5)
            ]
        |> onMenu model'

  -- The animation to scale the width of the meter
 UpdateMeter level ->
      let
        model' =
          { model 
             | storyLevel = level
             , storyChapter = currentStoryChapter level model.totalStoryChapters
          }
      in
        UI.animate
          |> UI.spring UI.wobbly
          |> UI.props
              [ Width (UI.to (toFloat (meterWidth model'))) Px
              ]
          |> onMeter model'
```
Then I have helper functions to update these two different kinds of animations.
```
onMenu =
  UI.forwardTo Animate .styleInfo (\w styleInfo -> { w | styleInfo = styleInfo }) 

onMeter =
  UI.forwardTo Animate .styleMeter (\w styleMeter -> { w | styleMeter = styleMeter }) 
```
I've hooked all this up to my UI, and, when I test them individually, they work just fine (actually, they look really amazing, thanks!!).
But, of course, I can only run one of these at a time in the `Animate` action
``` 
Animate action ->
  onMenu model action
 
  -- or
  -- onMeter model action
  -- ... but not both
```
Could you suggest a solution as to how I could get both these animations to work at the same time?
I'm pretty sure the answer lies somewhere in your Example #3, but it's a little too advanced for me and I haven't yet been able to work out how to apply it my current problem.

**Comment by mdgriffith** [comment]
Hello!

The issue here is that you're going to need an action to channel each animation separately.  So, instead of just `Animate`  you'll need `AnimateMeter` and `AnimateInfo`, each having their respective version of  `onMenu model action` or `onMenu model action`.

**Comment by kittykatattack** [comment]
Thank you, Sir, I will try that :)

**Comment by mdgriffith** [comment]
No problem.  Let me know if you run into any issues :)

**Comment by kittykatattack** [comment]
Marvelous! I've just implemented your suggestion and it works like a charm :)
