### ISSUE TITLE
animations involving translation don't work on iOS

### ISSUE THREAD

**Issue by bakkemo** [mdgriffith/elm-html-animation#5]
View Showcase.elm on iOS, the color animations work, translations do not.

**Comment by mdgriffith** [comment]
Thanks for the report.  I've just released 3.0.4 which has the proper vendor prefixes.  Does that solve the issue?

**Comment by bakkemo** [comment]
There is some noticable amout of tearing on the animations involving rotation and scaling on an ipad2, and the "rotate in all kinds of ways" disappears completely, but the vendor prefixes did fix the issue of no animation at all.

**Comment by mdgriffith** [comment]
I'm going to close this for now, but just for a follow up.

On my ipad the animations run smoothly and the "rotate in all kinds of ways" is still there, so I'm not sure what's going on.

I'm thinking of putting together a version of the showcase example using pure javascript and velocity.js to test if there are performance issues with elm-html-animation, or just with a browser/machine in general.
