### ISSUE TITLE
IE9 Compatibility

### ISSUE THREAD

**Issue by kittykatattack** [mdgriffith/elm-html-animation#6]
Hello!

I noticed this library doesn't work with IE9
That's fine, because I can easily provide fallback content.
But, just out of curiosity, I was wondering why?
Does elm-html-animation use CSS transitions and animation under-the-hood (IE9 doesn't support those)?

**Comment by mdgriffith** [comment]
Everything is inline css properties that are updated manually, no css animations.  

The library currently doesn't do any vendor prefixing, which should help in most cases.  I have a patch Im working on that includes this, so stay tuned :)  That being said, some properties may still not be supported by some browsers, even with a vendor prefix.  An example would be 3d transforms for IE9.

http://caniuse.com/#search=3d%20transforms

**Comment by mdgriffith** [comment]
OK, new version!

Would you mind updating to 3.0.4 and let me know if that helps?  I don't have access to IE9.

Basically, 2d transforms should work now for IE9, but 3d transforms probably still won't work.

**Comment by kittykatattack** [comment]
Thank you sir, I will try and let you know how it goes!
No worries.... I wish I didn't have access to iE9 either ;)

**Comment by kittykatattack** [comment]
I've just upgraded to 3.0.4 and the animations still don't work on IE9.
However, I just want to first confirm that it really is something in elm-html-animation that's preventing the animations from running, and not some other quirky code somewhere.
Let me run a few more focused tests and I'll get back to you.

**Comment by mdgriffith** [comment]
Any updates?

**Comment by kittykatattack** [comment]
Hi!
I wasn't able to do any more in-depth testing... but it turned out it didn't matter because we decided no longer to support IE9.
The animation works just fine in IE10 and up.
Maybe just close this issue till someone else brings it up again?

**Comment by mdgriffith** [comment]
I like that idea :)
